#!/bin/bash
echo "$PATH" | tr ':' '\n' | wc -l
echo "$PATH" | tr ':' '\n' | sort -u | wc -l
echo "$PATH" | tr ':' '\n' | sort -u | grep -c '^/usr/local/sbin$'
echo "$PATH" | tr ':' '\n' | sort -u | grep -c '^/usr/local/bin$'
