#!/usr/bin/env bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables for readability and maintainability
PATH_TO_FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer file using scp with disabled strict host key checking
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "${USERNAME}@${SERVER_IP}:~/"
