#!/usr/bin/env bash
# Script to install Nginx and configure a 301 redirect for /redirect_me

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to redirect /redirect_me
config="/etc/nginx/sites-available/default"
sed -i '/location \/ {/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' "$config"

# Restart Nginx to apply the changes
service nginx restart
