#!/usr/bin/env bash
# Setup UFW firewall to allow only SSH, HTTP, and HTTPS

apt-get update
apt-get install -y ufw

ufw default deny incoming
ufw default allow outgoing

ufw allow 22
ufw allow 80
ufw allow 443

ufw --force enable


